[env:wroom32e]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -D HARDWARE_TARGET="esp32-wroom"
lib_deps =
    bodmer/TFT_eSPI@^2.5.0
    ricmoo/QRCode@0.0.1
    bblanchon/ArduinoJson@^7.0.0
monitor_speed = 115200

